"""initial

Revision ID: ef6e6639b6ec
Revises: 253fcda6a156
Create Date: 2026-05-17 15:08:08.374970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef6e6639b6ec'
down_revision: Union[str, None] = '253fcda6a156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###